@startuml
skinparam style strictuml
skinparam classAttributelconSize 0
skinparam classFontStyle bold
hide enum methods
package view {
} 

package controller {
} 

package model
{
    package grid
    {
        class Grid
        {
            -m_size : Integer
            +createGrid(size : Integer)
        } 

        class Tile
        {
            -isHit : boolean
        }
        enum TileType
        {
            WATER
            LAND
        }
    }
    package placableObject
    {
        interface PlacableObject <<interface>>
        { 

        }
        class Trap <<abstract>> implements PlacableObject
        { 

        }
        class Blackhole extends Trap
        { 

        }
        class Tornado extends Trap
        { 

        }
        class Ship <<abstract>> implements PlacableObject
        {
            -m_size : Integer
            -m_pv : Integer
            -m_direction : Integer
            +<<Create>> Ship()
        }
        class AircraftCarrier extends Ship
        {
            +<<Create>> AircraftCarrier()
        }
        class Cruiser extends Ship
        {
            +<<Create>> Cruiser()
        }
        class Destroyer extends Ship
        {
            +<<Create>> Destroyer()
        }
        class Submarine extends Ship
        {
            +<<Create>> AircraftCarrier()
        }
        class TorpedoBoat extends Ship
        {
            +<<Create>> TorpedoBoat()
        } 

        class Weapon <<abstract>> implements PlacableObject
        {
            -m_name : String
        }
        class Bombe extends Weapon
        { 

        }
        class Sonar extends Weapon
        { 

        }
        enum ShipType
        {
        AIRCRAFTCARRIER
        CRUISER
        DESTROYER
        SUBMARINE
        TORPEDOBOAT
        }
        enum Direction
        {
        HORIZONTAL
        VERTICAL
	}
        enum TrapType
        {
        BLACKHOLE
        TORNADO
        }
        enum WeaponType
        {
        BOMBE
        SONAR
        }
    }
    package Player
    {
    class Player <<abstract>>
    {
	+PlaceBoatFix(gird : Grid)
	+PlaceBoatRandom(grid : Grid)
	+PlaceTrapFix(gird : Grid)
	+PlaceTrapRandom(grid : Grid)
	+PlaceWeaponRandom(grid: Grid)
    }
    class Human extends Player
    {
	+PlaceBoatCustom(grid : Grid)
	+PlaceTrapCustom(grid : Grid)
	+Attack(grid : Grid)
	+PlaceWeaponCustom(grid : Grid) 
    }
    class AI extends Player
    {
	+AttackRandom(grid : Grid)
	+AttackWithTought(grid: Grid)
    }
    }
    package Game {
	class Game {
		+startGame()
	}
	class Utils
	{
		+PlaceObject(object: PlacableObject, grid : Grid)
	}
    }
}
model.grid.Grid *--> "* -m_grid" model.grid.Tile : > is made of
model.grid.Tile *--> "1 -m_object" model.placableObject.PlacableObject: > has elements of the type
Grid *-> "1" model.grid.TileType : > is of the type\t
model.placableObject.Trap "1" o--> "-m_trapTypе" model.placableObject.TrapType: > is of the type
model.placableObject.Ship "1" o--> "-m_shipTyрe" model.placableObject.ShipType: > is of the type
model.placableObject.Ship "1" o--> "-m_direction" model.placableObject.Direction: > is in this direction
model.placableObject.Weapon "1" o--> "-m_weaponType" model.placableObject.WeaponType: > is of the typе
model.Player.Player .> model.grid.Grid : <<uses>>
@enduml